// =============================================================================
// Event & Alert Types
// =============================================================================
// Events are generated by the backend AI when anomalies are detected.
// The mobile app receives, stores, and displays them to the patient.
// Patient-facing text uses simple, non-clinical language.
// =============================================================================

/**
 * Severity levels for clinical events.
 * Maps to different notification and display behaviors.
 */
export type EventSeverity = 'info' | 'warning' | 'urgent' | 'critical';

/**
 * Categories of detectable anomalies.
 * These are the Phase 1 anomaly types that the backend AI can flag.
 */
export type AnomalyType =
  | 'bradycardia'       // Heart rate too low (<60 BPM sustained)
  | 'tachycardia'       // Heart rate too high (>100 BPM sustained)
  | 'irregular_rhythm'  // Irregular R-R intervals
  | 'signal_loss'       // Extended period of poor signal quality
  | 'pause'             // Significant pause in heartbeat (>2s)
  | 'unknown';          // Unclassified anomaly

/**
 * A clinical event detected by the backend AI.
 * This is what gets displayed to the patient as an alert.
 */
export interface ClinicalEvent {
  id: string;
  patientId: string;
  segmentId: string;

  /** Type of anomaly detected */
  type: AnomalyType;

  /** Severity level */
  severity: EventSeverity;

  /**
   * Patient-friendly title.
   * Example: "Unusual Heart Rhythm Detected"
   * (NOT: "Atrial fibrillation suspected")
   */
  title: string;

  /**
   * Patient-friendly description.
   * Example: "Your heart rhythm showed an unusual pattern for about 30 seconds.
   *           Your doctor has been notified."
   * (NOT: "Irregular R-R intervals with absence of P-waves detected")
   */
  description: string;

  /** When the anomaly occurred (ISO timestamp) */
  occurredAt: string;

  /** When the event was created by the backend */
  createdAt: string;

  /** Whether the patient has viewed this event */
  isRead: boolean;

  /** Whether the doctor has been notified */
  doctorNotified: boolean;

  /**
   * Recommended patient action in simple language.
   * Example: "No immediate action needed. Continue wearing your monitor."
   */
  patientAction: string | null;

  /** Measured BPM at the time of the event, if applicable */
  measuredBPM: number | null;

  /** Duration of the anomaly in seconds, if applicable */
  durationSeconds: number | null;
}

/**
 * Push notification payload received from the backend.
 */
export interface PushNotificationPayload {
  type: 'event' | 'status_update' | 'message';
  eventId?: string;
  severity?: EventSeverity;
  title: string;
  body: string;
}

/**
 * Local notification preferences set by the patient.
 */
export interface NotificationPreferences {
  /** Enable/disable all notifications */
  enabled: boolean;

  /** Vibrate on critical alerts */
  vibrateOnCritical: boolean;

  /** Sound on urgent/critical alerts */
  soundEnabled: boolean;

  /** Show info-level notifications */
  showInfoNotifications: boolean;

  /** Quiet hours - suppress non-critical notifications */
  quietHoursEnabled: boolean;
  quietHoursStart: string; // "HH:mm" format
  quietHoursEnd: string;   // "HH:mm" format
}
